import fs from 'node:fs'
import path from 'node:path'

const SQUAD_CSV_PATH = path.join(
  process.cwd(),
  '..',
  'player-data',
  'newcastle_squads_from_screenshots_players_positions.csv'
)

const CSV_PLAYER_NAME_BY_DISPLAY_NAME = new Map<string, string>([
  ['가브리엘 오베르탕', 'Gabriel Obertan'],
  ['가랑 쿠올', 'Garang Kuol'],
  ['가엘 비기리마나', 'Gael Bigirimana'],
  ['개리 브래디', 'Garry Brady'],
  ['개리 스피드', 'Gary Speed'],
  ['개리 콜드웰', 'Gary Caldwell'],
  ['그랜트 핸리', 'Grant Hanley'],
  ['기성용', 'Ki Sung-Yueng'],
  ['나빌 벤탈렙', 'Nabil Bentaleb'],
  ['나일 레인저', 'Nile Ranger'],
  ['나초 곤살레스', 'Nacho Gonzalez'],
  ['네이선 하커', 'Nathan Harker'],
  ['닉 볼테마데', 'Nick Woltemade'],
  ['닉 포프', 'Nick Pope'],
  ['니코스 다비자스', 'Nikos Dabizas'],
  ['니코스 파파바실리우', 'Nicos Papavasiliou'],
  ['니키 버트', 'Nicky Butt'],
  ['닐 맥더못', 'Neale McDermott'],
  ['놀베르토 솔라노', 'Nolberto Solano'],
  ['다니엘 랭글리', 'Daniel Langley'],
  ['다니엘 발레이서', 'Daniel Barlaser'],
  ['다니엘 코르도네', 'Daniel Cordone'],
  ['다니엘 테일러', 'Daniel Taylor'],
  ['다릴 머피', 'Daryl Murphy'],
  ['다릴 얀마트', 'Daryl Janmaat'],
  ['다비데 산톤', 'Davide Santon'],
  ['다비드 지놀라', 'David Ginola'],
  ['다비드 테리에', 'David Terrier'],
  ['대니 거스리', 'Danny Guthrie'],
  ['대니 로즈', 'Danny Rose'],
  ['대니 심프슨', 'Danny Simpson'],
  ['대런 앰브로즈', 'Darren Ambrose'],
  ['대런 피콕', 'Darren Peacock'],
  ['대런 허커비', 'Darren Huckerby'],
  ['댄 고슬링', 'Dan Gosling'],
  ['댄 번', 'Dan Burn'],
  ['데스 해밀턴', 'Des Hamilton'],
  ['데이미언 더프', 'Damien Duff'],
  ['데이비드 배티', 'David Batty'],
  ['데이비드 베하럴', 'David Beharall'],
  ['데이비드 에드가', 'David Edgar'],
  ['디디에 도미', 'Didier Domi'],
  ['디안드레 예들린', 'DeAndre Yedlin'],
  ['디에고 가빌란', 'Diego Gavilan'],
  ['디트마어 하만', 'Dietmar Hamann'],
  ['드와이트 게일', 'Dwight Gayle'],
  ['뎀바 바', 'Demba Ba'],
  ['던컨 퍼거슨', 'Duncan Ferguson'],
  ['라이언 도널드슨', 'Ryan Donaldson'],
  ['라이언 테일러', 'Ryan Taylor'],
  ['라이언 프레이저', 'Ryan Fraser'],
  ['라민 디아타', 'Lamine Diatta'],
  ['랄프 카이델', 'Ralf Keidel'],
  ['레미 카벨라', 'Remy Cabella'],
  ['레미 스트리트', 'Remie Streete'],
  ['레스 퍼디난드', 'Les Ferdinand'],
  ['레오 샤하르', 'Leo Shahar'],
  ['로랑 로베르', 'Laurent Robert'],
  ['로랑 샤르베', 'Laurent Charvet'],
  ['로리스 카리우스', 'Loris Karius'],
  ['로버트 리', 'Robert Lee'],
  ['로버트 엘리엇', 'Robert Elliot'],
  ['로비 엘리엇', 'Robbie Elliott'],
  ['로빈 헐버트', 'Robin Hulbert'],
  ['로이드 켈리', 'Lloyd Kelly'],
  ['로익 레미', 'Loic Remy'],
  ['로니 욘센', 'Ronny Johnsen'],
  ['롤란도 아론스', 'Rolando Aarons'],
  ['로맹 아말피타노', 'Romain Amalfitano'],
  ['롭 엘리엇', 'Rob Elliot'],
  ['루보미르 샤트카', 'Lubomir Satka'],
  ['루엘 폭스', 'Ruel Fox'],
  ['루이 사하', 'Louis Saha'],
  ['루이스 마일리', 'Lewis Miley'],
  ['루이스 카스', 'Lewis Cass'],
  ['루이스 홀', 'Lewis Hall'],
  ['루카스 더 볼레', 'Lucas De Bolle'],
  ['뤽 더 용', 'Luuk de Jong'],
  ['리 보이어', 'Lee Bowyer'],
  ['리 클라크', 'Lee Clark'],
  ['리언 베스트', 'Leon Best'],
  ['리오넬 페레스', 'Lionel Perez'],
  ['리처드 오피옹', 'Richard Offiong'],
  ['리암 깁슨', 'Liam Gibson'],
  ['마르틴 두브라브카', 'Martin Dubravka'],
  ['마이클 리처드슨', 'Michael Richardson'],
  ['마이클 브리지스', 'Michael Bridges'],
  ['마이클 오언', 'Michael Owen'],
  ['마이클 은디웨니', 'Michael Ndiweni'],
  ['마이클 제프리', 'Michael Jeffrey'],
  ['마이클 초프라', 'Michael Chopra'],
  ['마이클 호건슨', 'Michael Hoganson'],
  ['마이크 윌리엄슨', 'Mike Williamson'],
  ['마이크 후퍼', 'Mike Hooper'],
  ['마커스 매디슨', 'Marcus Maddison'],
  ['마크 길레스피', 'Mark Gillespie'],
  ['마크 도닝어', 'Mark Doninger'],
  ['마크 비두카', 'Mark Viduka'],
  ['마크 쿡', 'Mark Cook'],
  ['마크 호티거', 'Marc Hottiger'],
  ['마틴 브리튼', 'Martin Brittain'],
  ['마푸 양가-음비와', 'Mapou Yanga-Mbiwa'],
  ['마티외 드뷔시', 'Mathieu Debuchy'],
  ['말릭 치아우', 'Malick Thiaw'],
  ['맬컴 앨런', 'Malcolm Allen'],
  ['매튜 그리브', 'Matthew Grieve'],
  ['매튜 로빈슨', 'Matthew Robinson'],
  ['매튜 롱스태프', 'Matthew Longstaff'],
  ['매튜 패티슨', 'Matthew Pattison'],
  ['매티 롱스태프', 'Matty Longstaff'],
  ['매티 애플비', 'Matty Appleby'],
  ['매티 패티슨', 'Matty Pattison'],
  ['맷 리치', 'Matt Ritchie'],
  ['맷 타겟', 'Matt Targett'],
  ['맷 타깃', 'Matt Targett'],
  ['메흐디 아베이드', 'Mehdi Abeid'],
  ['모하메드 디아메', 'Mohamed Diame'],
  ['무사 시소코', 'Moussa Sissoko'],
  ['무토 요시노리', 'Yoshinori Muto'],
  ['미겔 알미론', 'Miguel Almiron'],
  ['미켈 메리노', 'Mikel Merino'],
  ['마사디오 하이다라', 'Massadio Haidara'],
  ['마츠 셀스', 'Matz Sels'],
  ['배리 베니슨', 'Barry Venison'],
  ['발렌티노 라자로', 'Valentino Lazaro'],
  ['벤 토저', 'Ben Tozer'],
  ['벤 파킨슨', 'Ben Parkinson'],
  ['뷔르논 아니타', 'Vurnon Anita'],
  ['브래든 인먼', 'Bradden Inman'],
  ['브래들리 오어', 'Bradley Orr'],
  ['브라이언 커', 'Brian Kerr'],
  ['브라이언 피나스', 'Brian Pinas'],
  ['브루노 기마랑이스', 'Bruno Guimaraes'],
  ['살로몬 론돈', 'Salomon Rondon'],
  ['산드로 토날리', 'Sandro Tonali'],
  ['새미 아메오비', 'Sammy Ameobi'],
  ['새미 아제이', 'Sammy Adjei'],
  ['샘 알라비', 'Sam Alabi'],
  ['샘 에이스턴', 'Sam Aiston'],
  ['샤를 은조그비아', "Charles N'Zogbia"],
  ['샤카 히슬롭', 'Shaka Hislop'],
  ['샹셀 음벰바', 'Chancel Mbemba'],
  ['션 니브', 'Sean Neave'],
  ['션 롱스태프', 'Sean Longstaff'],
  ['숀 니브', 'Sean Neave'],
  ['셰이 기븐', 'Shay Given'],
  ['셰이크 티오테', 'Cheik Tiote'],
  ['셰인 퍼거슨', 'Shane Ferguson'],
  ['셰프키 쿠키', 'Shefki Kuqi'],
  ['세바스티앙 바송', 'Sebastien Bassong'],
  ['세이두 둠비아', 'Seydou Doumbia'],
  ['셀레스틴 바바야로', 'Celestine Babayaro'],
  ['솔 캠벨', 'Sol Campbell'],
  ['숄라 아메오비', 'Shola Ameobi'],
  ['스벤 보트만', 'Sven Botman'],
  ['스콧 셀러스', 'Scott Sellars'],
  ['스콧 파커', 'Scott Parker'],
  ['스튜어트 그린', 'Stuart Green'],
  ['스튜어트 엘리엇', 'Stuart Elliott'],
  ['스튜어트 핀들레이', 'Stuart Findlay'],
  ['스튜어트 피어스', 'Stuart Pearce'],
  ['스티브 왓슨', 'Steve Watson'],
  ['스티브 하위', 'Steve Howey'],
  ['스티브 하퍼', 'Steve Harper'],
  ['스티븐 글래스', 'Stephen Glass'],
  ['스티븐 브레넌', 'Stephen Brennan'],
  ['스티븐 아일랜드', 'Stephen Ireland'],
  ['스티븐 카', 'Stephen Carr'],
  ['스티븐 콜드웰', 'Steven Caldwell'],
  ['스티븐 테일러', 'Steven Taylor'],
  ['시스코', 'Xisco'],
  ['시엠 더 용', 'Siem de Jong'],
  ['실뱅 디스탱', 'Sylvain Distin'],
  ['실뱅 마르보', 'Sylvain Marveaux'],
  ['실비오 마리치', 'Silvio Maric'],
  ['아담 해리슨', 'Adam Harrison'],
  ['아론 램스데일', 'Aaron Ramsdale'],
  ['아이반 토니', 'Ivan Toney'],
  ['아이작 헤이든', 'Isaac Hayden'],
  ['아요세 페레스', 'Ayoze Perez'],
  ['아슈라프 라자르', 'Achraf Lazaar'],
  ['아마두 디알로', 'Amadou Diallo'],
  ['안드레아스 안데르손', 'Andreas Andersson'],
  ['안드로스 타운센드', 'Andros Townsend'],
  ['안토니 엘랑가', 'Anthony Elanga'],
  ['안토니오 바레카', 'Antonio Barreca'],
  ['알랑 생막시맹', 'Allan Saint-Maximin'],
  ['알랭 고마', 'Alain Goma'],
  ['알렉산더 이삭', 'Alexander Isak'],
  ['알렉산다르 미트로비치', 'Aleksandar Mitrovic'],
  ['알렉스 길리아드', 'Alex Gilliead'],
  ['알렉스 매시', 'Alex Mathie'],
  ['알렉스 머피', 'Alex Murphy'],
  ['알레산드로 피스토네', 'Alessandro Pistone'],
  ['알베르트 루케', 'Albert Luque'],
  ['암디 파예', 'Amdy Faye'],
  ['압둘라예 파예', 'Abdoulaye Faye'],
  ['앨런 닐슨', 'Alan Neilson'],
  ['앨런 스미스', 'Alan Smith'],
  ['앨런 시어러', 'Alan Shearer'],
  ['앨런 암스트롱', 'Alun Armstrong'],
  ['앨런 오브라이언', "Alan O'Brien"],
  ['앤드류 콜', 'Andrew Cole'],
  ['앤디 그리핀', 'Andy Griffin'],
  ['앤디 오브라이언', "Andy O'Brien"],
  ['앤디 캐럴', 'Andy Carroll'],
  ['앤디 캐롤', 'Andy Carroll'],
  ['앤서니 고든', 'Anthony Gordon'],
  ['앤서니 엘랑가', 'Anthony Elanga'],
  ['앙리 세베', 'Henri Saivet'],
  ['앙투안 시비에르스키', 'Antoine Sibierski'],
  ['애덤 암스트롱', 'Adam Armstrong'],
  ['애덤 캠벨', 'Adam Campbell'],
  ['애덤 해리슨', 'Adam Harrison'],
  ['애덤 콜린', 'Adam Collin'],
  ['애런 램스데일', 'Aaron Ramsdale'],
  ['애런 휴즈', 'Aaron Hughes'],
  ['에밀 크라프트', 'Emil Krafth'],
  ['에이단 해리스', 'Aidan Harris'],
  ['에이든 해리스', 'Aidan Harris'],
  ['엘데르 크리스토방', 'Helder Cristovao'],
  ['엘레나 마르셀리노', 'Elena Marcelino'],
  ['엘리엇 앤더슨', 'Elliot Anderson'],
  ['엘리아스 쇠렌센', 'Elias Sorensen'],
  ['엠레', 'Emre'],
  ['엠마누엘 리비에르', 'Emmanuel Riviere'],
  ['오구치 오니예우', 'Oguchi Onyewu'],
  ['오디세아스 블라호디모스', 'Odysseas Vlachodimos'],
  ['오바페미 마르틴스', 'Obafemi Martins'],
  ['올레 쇠데르베리', 'Ole Soderberg'],
  ['올리비에 베르나르', 'Olivier Bernard'],
  ['올리비에 케멘', 'Olivier Kemen'],
  ['요르기오스 하랄람보스 게오르기아디스', 'Georgios Charalambos Georgiadis'],
  ['요안 시문 에드문손', 'Joan Simun Edmundsson'],
  ['요안 위사', 'Yoane Wissa'],
  ['요앙 구프랑', 'Yoan Gouffran'],
  ['요앙 카바예', 'Yohan Cabaye'],
  ['욘 달 토마손', 'Jon Dahl Tomasson'],
  ['우구 비아나', 'Hugo Viana'],
  ['워런 바튼', 'Warren Barton'],
  ['양쿠바 민테', 'Yankuba Minteh'],
  ['웨인 라우틀리지', 'Wayne Routledge'],
  ['웨인 퀸', 'Wayne Quinn'],
  ['윌리엄 오술라', 'William Osula'],
  ['이슬람 슬리마니', 'Islam Slimani'],
  ['이안 러시', 'Ian Rush'],
  ['자말 라셀스', 'Jamaal Lascelles'],
  ['자말 루이스', 'Jamal Lewis'],
  ['장알랭 붐송', 'Jean-Alain Boumsong'],
  ['잭 안윅', 'Jak Alnwick'],
  ['잭 영', 'Jack Young'],
  ['잭 콜백', 'Jack Colback'],
  ['저메인 제나스', 'Jermaine Jenas'],
  ['제러미', 'Geremi'],
  ['제레미', 'Geremi'],
  ['제이미 맥클렌', 'Jamie McClen'],
  ['제이미 마일리', 'Jamie Miley'],
  ['제이미 스테리', 'Jamie Sterry'],
  ['제이 터너-쿡', 'Jay Turner-Cooke'],
  ['제이콥 램지', 'Jacob Ramsey'],
  ['제이콥 머피', 'Jacob Murphy'],
  ['제이제이 후퍼', 'JJ Hooper'],
  ['제임스 밀너', 'James Milner'],
  ['제임스 코핑어', 'James Coppinger'],
  ['제임스 태버니어', 'James Tavernier'],
  ['제임스 트로이시', 'James Troisi'],
  ['제임스 퍼치', 'James Perch'],
  ['제임스 헌틀리', 'James Huntley'],
  ['제프 헨드릭', 'Jeff Hendrick'],
  ['조 윌록', 'Joe Willock'],
  ['조 화이트', 'Joe White'],
  ['조 켄드릭', 'Joe Kendrick'],
  ['조니 갓즈마크', 'Jonny Godsmark'],
  ['조나단 우드게이트', 'Jonathan Woodgate'],
  ['조르지니오 베이날둠', 'Georginio Wijnaldum'],
  ['조엘링톤', 'Joelinton'],
  ['조이 바튼', 'Joey Barton'],
  ['존 러디', 'John Ruddy'],
  ['존 반스', 'John Barnes'],
  ['존 베레스포드', 'John Beresford'],
  ['존 카렐서', 'John Karelse'],
  ['존조 셸비', 'Jonjo Shelvey'],
  ['지미 크로퍼드', 'Jimmy Crawford'],
  ['카젱가 루아루아', 'Kazenga Lua Lua'],
  ['칼 달로우', 'Karl Darlow'],
  ['칼 세런트', 'Carl Serrant'],
  ['칼 코트', 'Carl Cort'],
  ['캘럼 로버츠', 'Callum Roberts'],
  ['캘럼 윌리엄스', 'Callum Williams'],
  ['캘럼 윌슨', 'Callum Wilson'],
  ['캘빈 졸라', 'Calvin Zola'],
  ['커티스 굿', 'Curtis Good'],
  ['케네지', 'Kenedy'],
  ['케빈 갤러허', 'Kevin Gallacher'],
  ['케빈 놀란', 'Kevin Nolan'],
  ['케빈 음바부', 'Kevin Mbabu'],
  ['켈랜드 와츠', 'Kelland Watts'],
  ['코너 뉴턴', 'Conor Newton'],
  ['콜린 맥메너민', 'Colin McMenamin'],
  ['크레이그 무어', 'Craig Moore'],
  ['크레이그 벨라미', 'Craig Bellamy'],
  ['크리스 게이트', 'Kris Gate'],
  ['크리스 우드', 'Chris Wood'],
  ['크리스티안 바세다스', 'Christian Bassedas'],
  ['크리스티안 아추', 'Christian Atsu'],
  ['크리스 홀랜드', 'Chris Holland'],
  ['클라렌스 아쿠냐', 'Clarence Acuna'],
  ['클라우지우 카사파', 'Claudio Cacapa'],
  ['키스 길레스피', 'Keith Gillespie'],
  ['키어런 다이어', 'Kieron Dyer'],
  ['키어런 클라크', 'Ciaran Clark'],
  ['키어런 트리피어', 'Kieran Trippier'],
  ['타마스 카다르', 'Tamas Kadar'],
  ['타이터스 브램블', 'Titus Bramble'],
  ['토니 디닝', 'Tony Dinning'],
  ['토니 케이그', 'Tony Caig'],
  ['토마스 앨런', 'Thomas Allan'],
  ['토머스 앨런', 'Thomas Allan'],
  ['토미 라이트', 'Tommy Wright'],
  ['테무리 케츠바이아', 'Temuri Ketsbaia'],
  ['트래비스 헤르네스', 'Travis Hernes'],
  ['트레반 사누시', 'Trevan Sanusi'],
  ['트레번 사누시', 'Trevan Sanusi'],
  ['트레소르 로마나 루아 루아', 'Tresor Lomana Lua Lua'],
  ['티노 리브라멘토', 'Tino Livramento'],
  ['팀 크룰', 'Tim Krul'],
  ['파벨 스르니체크', 'Pavel Srnicek'],
  ['파브리시오 콜로치니', 'Fabricio Coloccini'],
  ['파브리스 팡크라트', 'Fabrice Pancrate'],
  ['파비안 셰어', 'Fabian Schar'],
  ['파비오 잠블레라', 'Fabio Zamblera'],
  ['파우스티노 아스프리야', 'Faustino Asprilla'],
  ['파쿤도 페레이라', 'Facundo Ferreyra'],
  ['파피스 뎀바 시세', 'Papiss Demba Cisse'],
  ['파피스 시세', 'Papiss Cisse'],
  ['파트릭 클라위버르트', 'Patrick Kluivert'],
  ['박승수', 'Park Seung-Soo'],
  ['패디 켈리', 'Paddy Kelly'],
  ['패트릭 맥러플린', 'Patrick McLaughlin'],
  ['페데리코 페르난데스', 'Federico Fernandez'],
  ['폴 달글리시', 'Paul Dalglish'],
  ['폴 더밋', 'Paul Dummett'],
  ['폴 로빈슨', 'Paul Robinson'],
  ['폴 배럿', 'Paul Barrett'],
  ['폴 브레이스웰', 'Paul Bracewell'],
  ['폴 브레이슨', 'Paul Brayson'],
  ['폴 킷슨', 'Paul Kitson'],
  ['폴 헌팅턴', 'Paul Huntington'],
  ['푸마사', 'Fumaca'],
  ['프랭크 위아페 단콰', 'Frank Wiafe Danquah'],
  ['프레이저 포스터', 'Fraser Forster'],
  ['프레디 우드먼', 'Freddie Woodman'],
  ['프레디 우드먼', 'Freddy Woodman'],
  ['플로리앙 르죈', 'Florian Lejeune'],
  ['플로리앙 토뱅', 'Florian Thauvin'],
  ['필 에어리', 'Phil Airey'],
  ['필리프 알베르', 'Phillipe Albert'],
  ['피터 라마지', 'Peter Ramage'],
  ['피터 뢰벤크란츠', 'Peter Lovenkrands'],
  ['피터 비어즐리', 'Peter Beardsley'],
  ['피터 킨', 'Peter Keen'],
  ['피츠 홀', 'Fitz Hall'],
  ['하리스 부키치', 'Haris Vuckic'],
  ['하비 반스', 'Harvey Barnes'],
  ['하비브 베예', 'Habib Beye'],
  ['하비에르 만키요', 'Javier Manquillo'],
  ['하템 벤 아르파', 'Hatem Ben Arfa'],
  ['해리슨 애쉬비', 'Harrison Ashby'],
  ['해리슨 애슈비', 'Harrison Ashby'],
  ['헤수스 가메스', 'Jesus Gamez'],
  ['호나스 구티에레스', 'Jonas Gutierrez'],
  ['호세 엔리케', 'Jose Enrique'],
  ['호셀루', 'Joselu'],
  ['야신 벤 엘므하니', 'Yasin Ben El-Mhanni'],
])

let cachedSeasonsByCsvName: Map<string, string[]> | null = null

function getSeasonsByCsvName(): Map<string, string[]> {
  if (cachedSeasonsByCsvName) return cachedSeasonsByCsvName

  const seasonsByCsvName = new Map<string, string[]>()
  const csv = fs.readFileSync(SQUAD_CSV_PATH, 'utf8').trim().split(/\r?\n/).slice(1)

  for (const row of csv) {
    const [season, player] = row.split(',')
    if (!season || !player) continue
    seasonsByCsvName.set(player, [...(seasonsByCsvName.get(player) ?? []), season])
  }

  cachedSeasonsByCsvName = seasonsByCsvName
  return seasonsByCsvName
}

export function getPlayerSeasonsFromSquadCsv(displayName: string): string[] {
  const csvName = CSV_PLAYER_NAME_BY_DISPLAY_NAME.get(displayName)
  if (!csvName) return []

  return getSeasonsByCsvName().get(csvName) ?? []
}
